<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRjxITfX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRjxITfX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRjxITfX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRjxITfX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRjxITfX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RjxITfX',
    'container.build_id' => '1adf9bc5',
    'container.build_time' => 1573575258,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRjxITfX');
