<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIl4qfVT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIl4qfVT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIl4qfVT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIl4qfVT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIl4qfVT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Il4qfVT',
    'container.build_id' => '8435018f',
    'container.build_time' => 1570971716,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIl4qfVT');
