<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBuxYRe8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBuxYRe8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBuxYRe8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBuxYRe8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBuxYRe8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BuxYRe8',
    'container.build_id' => 'fbd3dcc9',
    'container.build_time' => 1570969064,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBuxYRe8');
